version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "main"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "main"
    cooldown:
      default-days: 7
    groups:
      gomod:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "v2-edge"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "v2-edge"
    cooldown:
      default-days: 7
    groups:
      gomod:
        patterns:
          - "*"
