version: "2"
linters:
  enable:
    - godot
    - misspell
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/canonical/microcloud/microcloud)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
