version: "2"
linters:
  enable:
    - godot
    - misspell
    - perfsprint
    - prealloc
    - testifylint
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: "ST1005:" # ST1005: error strings should not be capitalized
  settings:
    testifylint:
      disable:
        - float-compare
        - require-error
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/canonical/microcloud/microcloud)
