# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    golang: "1.23"
    python: "3.12"
  commands:
      - git fetch --unshallow || true
      - cd doc && make integrate
      - cd doc/integration/lxd/ && go build -ldflags "-s -w" -o trimpath -o lxc.bin ./lxc
      # Pretend that woke is installed - we don't need it for building
      # (workaround until https://github.com/canonical/microovn/pull/168 is merged
      # and https://github.com/canonical/microceph/pull/400 is restored)
      - ln -s /bin/true doc/integration/microovn/docs/woke
      - ln -s /bin/true doc/integration/microceph/docs/woke
      - make doc-html-rtd PATH=$PATH:.

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: dirhtml
  configuration: doc/conf.py
  fail_on_warning: true

# If using Sphinx, optionally build your docs in additional formats such as PDF
#formats:
#   - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: doc/.sphinx/requirements.txt
