import datetime
import os
import yaml

############################
# MicroCloud custom configuration #
############################

import sys
from git import Repo
import re

sys.path.append('./')
sys.path.append('.sphinx/')

with open('../version/version.go') as f:
    match = re.search(r'RawVersion = "([^"]+)"', f.read())
    version = match.group(1) if match else ''


#######################
# Project information #
#######################

project = 'MicroCloud'
author = 'Canonical Ltd.'

# Sidebar documentation title; best kept reasonably short
# To disable the title, set to an empty string.
html_title = project + ' documentation ' + version

# Copyright string; shown at the bottom of the page
copyright = '2014-%s AGPL-3.0, %s' % (datetime.date.today().year, author)

# Documentation website URL

version_slug = f'{os.environ.get("READTHEDOCS_VERSION", "local")}'

slug = 'microcloud/docs'

html_baseurl = f'https://canonical.com/microcloud/docs/{version_slug}/'

# OpenGraph metadata used for social sharing previews
ogp_site_url = html_baseurl
ogp_site_name = html_title
ogp_image = f'https://canonical.com/microcloud/docs/{version_slug}/_static/microcloud_tag.png'

html_favicon = '_static/favicon.png'

html_context = {
    'product_page': 'canonical.com/microcloud',
    'product_tag': '_static/microcloud_tag.png',

    'discourse': 'https://discourse.ubuntu.com/c/lxd/microcloud/',
    'discourse_prefix': {
        'ubuntu': 'https://discourse.ubuntu.com/t/',
        'lxc': 'https://discuss.linuxcontainers.org/t/',
    },

    'mattermost': '',
    'matrix': '',

    'github_url': 'https://github.com/canonical/microcloud',
    'repo_default_branch': 'main',
    'repo_folder': '/doc/',

    # Required for feedback button
    'github_issues': 'enabled',

    # Enables listing contributors on individual pages
    # This feature is deprecated and will be removed in the future
    'display_contributors': False,

    'sequential_nav': 'both',
}

html_extra_path = ['_extra']

# Enables the pencil icon to edit pages on GitHub, shown at the top of each page
# html_theme_options = {
#     'source_edit_link': html_context['github_url']
# }

#######################
# Sitemap configuration: https://sphinx-sitemap.readthedocs.io/
#######################

# sphinx-sitemap uses html_baseurl (set earlier in this file) to generate the full URL for each page:

sitemap_url_scheme = '{link}'

# Include `lastmod` dates in the sitemap:
sitemap_show_lastmod = True

# Exclude generated pages from the sitemap:
sitemap_excludes = [
    '404/',
    'genindex/',
    'search/',
]

# Add more pages to sitemap_excludes if needed. Wildcards are supported.
# For example, to exclude module pages generated by autodoc, add '_modules/*'.

#######################
# Template and asset locations
#######################

html_static_path = ['_static']


#############
# Redirects #
#############

# Add redirects to the 'redirects.txt' file
# https://sphinxext-rediraffe.readthedocs.io/en/latest/

# To set up redirects in the Read the Docs project dashboard:
# https://docs.readthedocs.io/en/stable/guides/redirects.html

rediraffe_redirects = 'redirects.txt'

# Strips '/index.html' from destination URLs when building with 'dirhtml'
rediraffe_dir_only = True

###########################
# Link checker exceptions #
###########################

# Always ignore these links
linkcheck_ignore = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    # These links may fail from time to time
    'https://ceph.io',
    # Rejects us always with a "Connection aborted"
    r'https://charmhub\.io/.*',
    # Cloudflare protection on SourceForge domains often block linkcheck
    r'https://.*\.sourceforge\.(net|io)/.*',
    # These links often fail due to infra issues or protection measures 
    r'https://ubuntu\.com.*',
    r'https://canonical\.com.*',
    r'https://snapcraft\.io.*',
    # Ignore so that we can link change log in release notes before a release is ready
    r'https://github\.com/canonical/microcloud/compare.*',
]

# Pages on which to ignore anchors (check the link without the anchor)
linkcheck_anchors_ignore_for_url = [
    r'https://snapcraft\.io/docs/.*',
    r'https://github\.com/.*',
    r'https://charmhub\.io/.*',
]

# Increase linkcheck rate limit timeout max, default when unset is 300
# https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_timeout
linkcheck_rate_limit_timeout = 600

# Increase linkcheck retries, default when unset is 1
# https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_retries
linkcheck_retries = 3

# Increase the duration, in seconds, that the linkcheck builder will wait for a response after each hyperlink request.
# Default when unset is 30
# https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_timeout
linkcheck_timeout = 45


########################
# Configuration extras #
########################

extensions = [
    'canonical_sphinx',
    'notfound.extension',
    'sphinx_design',
    'sphinx_rerediraffe',
    'sphinx_tabs.tabs',
    'sphinxcontrib.jquery',
    'sphinxext.opengraph',
    'sphinx_related_links',
    'sphinx_roles',
    'sphinx_terminal',
    'sphinx_youtube_links',
    'sphinxcontrib.cairosvgconverter',
    'sphinx_last_updated_by_git',
    'sphinx.ext.intersphinx',
    'sphinx_sitemap',
    'myst_parser',
]

# Excludes files or directories from processing
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    '.sphinx',
    '.venv',
    'reference/release-notes/release-notes-template.md',
    'integration',
    'README.md',
]

html_css_files = [
    'https://assets.ubuntu.com/v1/d86746ef-cookie_banner.css',
]

if os.environ.get('SINGLE_BUILD') != 'True':
    html_css_files.append('override-header.css')

html_js_files = [
    'https://assets.ubuntu.com/v1/287a5e8f-bundle.js',
    'js/rtd-versions-flyout.js',
    "js/overwrite_links.js",
]

# Feedback button at the top; enabled by default
# To disable the button, uncomment the line below:

# disable_feedback_button = True

# Define a :center: role that can be used to center the content of table cells.
rst_prolog = '''
.. role:: center
   :class: align-center
.. role:: h2
    :class: hclass2
.. role:: woke-ignore
    :class: woke-ignore
.. role:: vale-ignore
    :class: vale-ignore
'''

# Load substitutions from YAML file
if os.path.exists('./reuse/substitutions.yaml'):
    with open('./reuse/substitutions.yaml', 'r') as fd:
        myst_substitutions = yaml.safe_load(fd.read())

############################################################
### Styling
############################################################

# Find the current builder
builder = 'dirhtml'
if '-b' in sys.argv:
    builder = sys.argv[sys.argv.index('-b')+1]

# Setting templates_path for epub makes the build fail
if builder == 'dirhtml' or builder == 'html':
    templates_path = ['_templates']
    if os.environ.get('SINGLE_BUILD') != 'True':
        templates_path.insert(0, 'integration/microcloud/_templates')
    notfound_template = '404.html'

##########################################
### Misc MicroCloud custom configuration #
##########################################

# Use custom 404 page text
notfound_context = {
    'title': 'Page not found',
    'body': '<p><strong>Sorry, but the documentation page that you are looking for was not found.</strong></p>\n\n<p>Documentation changes over time, and pages are moved around. We try to redirect you to the updated content where possible, but unfortunately, that didn\'t work this time (maybe because the content you were looking for does not exist in this version of the documentation).</p>\n<p>You can try to use the navigation to locate the content you\'re looking for, or search for a similar page.</p>\n',
}

# Intersphinx setup differs for different builds to optimize use with integrated docs  
if ('SINGLE_BUILD' in os.environ and os.environ['SINGLE_BUILD'] == 'True'):
    intersphinx_mapping = {
        'lxd': ('https://canonical.com/lxd/docs/latest/', None),
        'microceph': ('https://documentation.ubuntu.com/canonical-microceph/latest/', None),
        'microovn': ('https://canonical-microovn.readthedocs-hosted.com/en/latest/', None),
    }
elif ('READTHEDOCS' in os.environ) and (os.environ['READTHEDOCS'] == 'True'):
    intersphinx_mapping = {
        'lxd': (os.environ['PATH_PREFIX'] + 'lxd/', os.environ['READTHEDOCS_OUTPUT'] + 'html/lxd/objects.inv'),
        'microceph': (os.environ['PATH_PREFIX'] + 'microceph/', os.environ['READTHEDOCS_OUTPUT'] + 'html/microceph/objects.inv'),
        'microovn': (os.environ['PATH_PREFIX'] + 'microovn/', os.environ['READTHEDOCS_OUTPUT'] + 'html/microovn/objects.inv'),
    }
else:
    intersphinx_mapping = {
        'lxd': ('/lxd/', '_build/lxd/objects.inv'),
        'microceph': ('/microceph/', '_build/microceph/objects.inv'),
        'microovn': ('/microovn/', '_build/microovn/objects.inv'),
    }

# Add intersphinx mappings for docs sets not part of the MicroCloud integrated docs here:

base_intersphinx = {
    'ceph': ('https://docs.ceph.com/en/latest/', None),
    'snap': ('https://snapcraft.io/docs/', None),
}

intersphinx_mapping.update(base_intersphinx)

# Update html_context for integrated builds and add the "integrated" tag
if os.environ.get('SINGLE_BUILD') != 'True':
    exec(compile(source=open('.sphinx/_integration/add_config.py').read(), filename='.sphinx/_integration/add_config.py', mode='exec'))
    # MicroCloud docs are at the URL root, so override the relative paths to sibling doc sets
    html_context['lxd_path'] = 'lxd'
    html_context['lxd_tag'] = 'lxd/_static/lxd_tag.png'
    html_context['microceph_path'] = 'microceph'
    html_context['microceph_tag'] = 'microceph/_static/tag.png'
    html_context['microovn_path'] = 'microovn'
    html_context['microovn_tag'] = 'microovn/_static/microovn.png'
    html_static_path.append('integration/microcloud/_static')
    tags.add('integrated')

# SwaggerUI configuration
if os.environ.get('READTHEDOCS'):
    swagger_url_scheme = '/microcloud/latest/api/#{{path}}'
else:
    swagger_url_scheme = '/api/#{{path}}'

myst_url_schemes = {
    'http': None,
    'https': None,
    'swagger': swagger_url_scheme,
}

# Download and link swagger-ui files
if not os.path.isdir('.sphinx/deps/swagger-ui'):
    Repo.clone_from('https://github.com/swagger-api/swagger-ui', '.sphinx/deps/swagger-ui', depth=1)

os.makedirs('_static/swagger-ui/', exist_ok=True)

if not os.path.islink('_static/swagger-ui/swagger-ui-bundle.js'):
    os.symlink('../../.sphinx/deps/swagger-ui/dist/swagger-ui-bundle.js', '_static/swagger-ui/swagger-ui-bundle.js')
if not os.path.islink('_static/swagger-ui/swagger-ui-standalone-preset.js'):
    os.symlink('../../.sphinx/deps/swagger-ui/dist/swagger-ui-standalone-preset.js', '_static/swagger-ui/swagger-ui-standalone-preset.js')
if not os.path.islink('_static/swagger-ui/swagger-ui.css'):
    os.symlink('../../.sphinx/deps/swagger-ui/dist/swagger-ui.css', '_static/swagger-ui/swagger-ui.css')


# Version label shown in the RTD flyout next to "default", in parentheses.
# Set the FLYOUT_DEFAULT_VERSION_LABEL environment variable in the RTD project dashboard.
html_context['flyout_default_version_label'] = os.environ.get('FLYOUT_DEFAULT_VERSION_LABEL', '')
