package database

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"github.com/canonical/microcluster/v2/cluster"
	"net/http"
	"strings"

	"github.com/canonical/lxd/lxd/db/query"
	"github.com/canonical/lxd/shared/api"
)

var _ = api.ServerEnvironment{}

var clusterManagerObjects = cluster.RegisterStmt(`
SELECT cluster_manager.id, cluster_manager.addresses, cluster_manager.server_cert_fingerprint, cluster_manager.update_interval_seconds
  FROM cluster_manager
  ORDER BY cluster_manager.id
`)

var clusterManagerObjectsByID = cluster.RegisterStmt(`
SELECT cluster_manager.id, cluster_manager.addresses, cluster_manager.server_cert_fingerprint, cluster_manager.update_interval_seconds
  FROM cluster_manager
  WHERE ( cluster_manager.id = ? )
  ORDER BY cluster_manager.id
`)

var clusterManagerID = cluster.RegisterStmt(`
SELECT cluster_manager.id FROM cluster_manager
  WHERE cluster_manager.id = ?
`)

var clusterManagerDeleteByID = cluster.RegisterStmt(`
DELETE FROM cluster_manager WHERE id = ?
`)

var clusterManagerCreate = cluster.RegisterStmt(`
INSERT INTO cluster_manager (addresses, server_cert_fingerprint, update_interval_seconds)
  VALUES (?, ?, ?)
`)

var clusterManagerUpdate = cluster.RegisterStmt(`
UPDATE cluster_manager
  SET addresses = ?, server_cert_fingerprint = ?, update_interval_seconds = ?
 WHERE id = ?
`)

// clusterManagerColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the ClusterManager entity.
func clusterManagerColumns() string {
	return "cluster_manager.id, cluster_manager.addresses, cluster_manager.server_cert_fingerprint, cluster_manager.update_interval_seconds"
}

// getClusterManagers can be used to run handwritten sql.Stmts to return a slice of objects.
func getClusterManagers(ctx context.Context, stmt *sql.Stmt, args ...any) ([]ClusterManager, error) {
	objects := make([]ClusterManager, 0)

	dest := func(scan func(dest ...any) error) error {
		c := ClusterManager{}
		err := scan(&c.ID, &c.Addresses, &c.ServerCertFingerprint, &c.UpdateIntervalSeconds)
		if err != nil {
			return err
		}

		objects = append(objects, c)

		return nil
	}

	err := query.SelectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cluster_manager\" table: %w", err)
	}

	return objects, nil
}

// getClusterManagersRaw can be used to run handwritten query strings to return a slice of objects.
func getClusterManagersRaw(ctx context.Context, tx *sql.Tx, sql string, args ...any) ([]ClusterManager, error) {
	objects := make([]ClusterManager, 0)

	dest := func(scan func(dest ...any) error) error {
		c := ClusterManager{}
		err := scan(&c.ID, &c.Addresses, &c.ServerCertFingerprint, &c.UpdateIntervalSeconds)
		if err != nil {
			return err
		}

		objects = append(objects, c)

		return nil
	}

	err := query.Scan(ctx, tx, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cluster_manager\" table: %w", err)
	}

	return objects, nil
}

// GetClusterManagers returns all available ClusterManagers.
// generator: ClusterManager GetMany
func GetClusterManagers(ctx context.Context, tx *sql.Tx, filters ...ClusterManagerFilter) ([]ClusterManager, error) {
	var err error

	// Result slice.
	objects := make([]ClusterManager, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = cluster.Stmt(tx, clusterManagerObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"clusterManagerObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.ID != nil {
			args = append(args, []any{filter.ID}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, clusterManagerObjectsByID)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"clusterManagerObjectsByID\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(clusterManagerObjectsByID)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"clusterManagerObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.ID == nil {
			return nil, fmt.Errorf("Cannot filter on empty ClusterManagerFilter")
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getClusterManagers(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getClusterManagersRaw(ctx, tx, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cluster_manager\" table: %w", err)
	}

	return objects, nil
}

// GetClusterManager returns the ClusterManager with the given key.
// generator: ClusterManager GetOne
func GetClusterManager(ctx context.Context, tx *sql.Tx, id int64) (*ClusterManager, error) {
	filter := ClusterManagerFilter{}
	filter.ID = &id

	objects, err := GetClusterManagers(ctx, tx, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"cluster_manager\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, api.StatusErrorf(http.StatusNotFound, "ClusterManager not found")
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"cluster_manager\" entry matches")
	}
}

// GetClusterManagerID return the ID of the ClusterManager with the given key.
// generator: ClusterManager ID
func GetClusterManagerID(ctx context.Context, tx *sql.Tx, id int64) (int64, error) {
	stmt, err := cluster.Stmt(tx, clusterManagerID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"clusterManagerID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, id)
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, api.StatusErrorf(http.StatusNotFound, "ClusterManager not found")
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"cluster_manager\" ID: %w", err)
	}

	return id, nil
}

// ClusterManagerExists checks if a ClusterManager with the given key exists.
// generator: ClusterManager Exists
func ClusterManagerExists(ctx context.Context, tx *sql.Tx, id int64) (bool, error) {
	_, err := GetClusterManagerID(ctx, tx, id)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}

		return false, err
	}

	return true, nil
}

// CreateClusterManager adds a new ClusterManager to the database.
// generator: ClusterManager Create
func CreateClusterManager(ctx context.Context, tx *sql.Tx, object ClusterManager) (int64, error) {
	// Check if a ClusterManager with the same key exists.
	exists, err := ClusterManagerExists(ctx, tx, object.ID)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"cluster_manager\" entry already exists")
	}

	args := make([]any, 3)

	// Populate the statement arguments.
	args[0] = object.Addresses
	args[1] = object.ServerCertFingerprint
	args[2] = object.UpdateIntervalSeconds

	// Prepared statement to use.
	stmt, err := cluster.Stmt(tx, clusterManagerCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"clusterManagerCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"cluster_manager\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"cluster_manager\" entry ID: %w", err)
	}

	return id, nil
}

// UpdateClusterManager updates the ClusterManager matching the given key parameters.
// generator: ClusterManager Update
func UpdateClusterManager(ctx context.Context, tx *sql.Tx, id int64, object ClusterManager) error {
	id, err := GetClusterManagerID(ctx, tx, id)
	if err != nil {
		return err
	}

	stmt, err := cluster.Stmt(tx, clusterManagerUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"clusterManagerUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.Addresses, object.ServerCertFingerprint, object.UpdateIntervalSeconds, id)
	if err != nil {
		return fmt.Errorf("Update \"cluster_manager\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}

// DeleteClusterManager deletes the ClusterManager matching the given key parameters.
// generator: ClusterManager DeleteOne-by-ID
func DeleteClusterManager(ctx context.Context, tx *sql.Tx, id int64) error {
	stmt, err := cluster.Stmt(tx, clusterManagerDeleteByID)
	if err != nil {
		return fmt.Errorf("Failed to get \"clusterManagerDeleteByID\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(id)
	if err != nil {
		return fmt.Errorf("Delete \"cluster_manager\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return api.StatusErrorf(http.StatusNotFound, "ClusterManager not found")
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d ClusterManager rows instead of 1", n)
	}

	return nil
}
