package database

// The code below was generated by lxd-generate - DO NOT EDIT!

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"github.com/canonical/microcluster/v2/cluster"
	"net/http"
	"strings"

	"github.com/canonical/lxd/lxd/db/query"
	"github.com/canonical/lxd/shared/api"
)

var _ = api.ServerEnvironment{}

var siteObjects = cluster.RegisterStmt(`
SELECT sites.id, sites.name, sites.addresses, sites.type, sites.description
  FROM sites
  ORDER BY sites.name
`)

var siteObjectsByName = cluster.RegisterStmt(`
SELECT sites.id, sites.name, sites.addresses, sites.type, sites.description
  FROM sites
  WHERE ( sites.name = ? )
  ORDER BY sites.name
`)

var siteID = cluster.RegisterStmt(`
SELECT sites.id FROM sites
  WHERE sites.name = ?
`)

var siteCreate = cluster.RegisterStmt(`
INSERT INTO sites (name, addresses, type, description)
  VALUES (?, ?, ?, ?)
`)

var siteDeleteByName = cluster.RegisterStmt(`
DELETE FROM sites WHERE name = ?
`)

var siteUpdate = cluster.RegisterStmt(`
UPDATE sites
  SET name = ?, addresses = ?, type = ?, description = ?
 WHERE id = ?
`)

// siteColumns returns a string of column names to be used with a SELECT statement for the entity.
// Use this function when building statements to retrieve database entries matching the Site entity.
func siteColumns() string {
	return "sites.id, sites.name, sites.addresses, sites.type, sites.description"
}

// getSites can be used to run handwritten sql.Stmts to return a slice of objects.
func getSites(ctx context.Context, stmt *sql.Stmt, args ...any) ([]Site, error) {
	objects := make([]Site, 0)

	dest := func(scan func(dest ...any) error) error {
		s := Site{}
		err := scan(&s.ID, &s.Name, &s.Addresses, &s.Type, &s.Description)
		if err != nil {
			return err
		}

		objects = append(objects, s)

		return nil
	}

	err := query.SelectObjects(ctx, stmt, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"sites\" table: %w", err)
	}

	return objects, nil
}

// getSitesRaw can be used to run handwritten query strings to return a slice of objects.
func getSitesRaw(ctx context.Context, tx *sql.Tx, sql string, args ...any) ([]Site, error) {
	objects := make([]Site, 0)

	dest := func(scan func(dest ...any) error) error {
		s := Site{}
		err := scan(&s.ID, &s.Name, &s.Addresses, &s.Type, &s.Description)
		if err != nil {
			return err
		}

		objects = append(objects, s)

		return nil
	}

	err := query.Scan(ctx, tx, sql, dest, args...)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"sites\" table: %w", err)
	}

	return objects, nil
}

// GetSites returns all available Sites.
// generator: Site GetMany
func GetSites(ctx context.Context, tx *sql.Tx, filters ...SiteFilter) ([]Site, error) {
	var err error

	// Result slice.
	objects := make([]Site, 0)

	// Pick the prepared statement and arguments to use based on active criteria.
	var sqlStmt *sql.Stmt
	args := []any{}
	queryParts := [2]string{}

	if len(filters) == 0 {
		sqlStmt, err = cluster.Stmt(tx, siteObjects)
		if err != nil {
			return nil, fmt.Errorf("Failed to get \"siteObjects\" prepared statement: %w", err)
		}
	}

	for i, filter := range filters {
		if filter.Name != nil && filter.Type == nil {
			args = append(args, []any{filter.Name}...)
			if len(filters) == 1 {
				sqlStmt, err = cluster.Stmt(tx, siteObjectsByName)
				if err != nil {
					return nil, fmt.Errorf("Failed to get \"siteObjectsByName\" prepared statement: %w", err)
				}

				break
			}

			query, err := cluster.StmtString(siteObjectsByName)
			if err != nil {
				return nil, fmt.Errorf("Failed to get \"siteObjects\" prepared statement: %w", err)
			}

			parts := strings.SplitN(query, "ORDER BY", 2)
			if i == 0 {
				copy(queryParts[:], parts)
				continue
			}

			_, where, _ := strings.Cut(parts[0], "WHERE")
			queryParts[0] += "OR" + where
		} else if filter.Type == nil && filter.Name == nil {
			return nil, fmt.Errorf("Cannot filter on empty SiteFilter")
		} else {
			return nil, fmt.Errorf("No statement exists for the given Filter")
		}
	}

	// Select.
	if sqlStmt != nil {
		objects, err = getSites(ctx, sqlStmt, args...)
	} else {
		queryStr := strings.Join(queryParts[:], "ORDER BY")
		objects, err = getSitesRaw(ctx, tx, queryStr, args...)
	}

	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"sites\" table: %w", err)
	}

	return objects, nil
}

// GetSite returns the Site with the given key.
// generator: Site GetOne
func GetSite(ctx context.Context, tx *sql.Tx, name string) (*Site, error) {
	filter := SiteFilter{}
	filter.Name = &name

	objects, err := GetSites(ctx, tx, filter)
	if err != nil {
		return nil, fmt.Errorf("Failed to fetch from \"sites\" table: %w", err)
	}

	switch len(objects) {
	case 0:
		return nil, api.StatusErrorf(http.StatusNotFound, "Site not found")
	case 1:
		return &objects[0], nil
	default:
		return nil, fmt.Errorf("More than one \"sites\" entry matches")
	}
}

// GetSiteID return the ID of the Site with the given key.
// generator: Site ID
func GetSiteID(ctx context.Context, tx *sql.Tx, name string) (int64, error) {
	stmt, err := cluster.Stmt(tx, siteID)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"siteID\" prepared statement: %w", err)
	}

	row := stmt.QueryRowContext(ctx, name)
	var id int64
	err = row.Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return -1, api.StatusErrorf(http.StatusNotFound, "Site not found")
	}

	if err != nil {
		return -1, fmt.Errorf("Failed to get \"sites\" ID: %w", err)
	}

	return id, nil
}

// SiteExists checks if a Site with the given key exists.
// generator: Site Exists
func SiteExists(ctx context.Context, tx *sql.Tx, name string) (bool, error) {
	_, err := GetSiteID(ctx, tx, name)
	if err != nil {
		if api.StatusErrorCheck(err, http.StatusNotFound) {
			return false, nil
		}

		return false, err
	}

	return true, nil
}

// CreateSite adds a new Site to the database.
// generator: Site Create
func CreateSite(ctx context.Context, tx *sql.Tx, object Site) (int64, error) {
	// Check if a Site with the same key exists.
	exists, err := SiteExists(ctx, tx, object.Name)
	if err != nil {
		return -1, fmt.Errorf("Failed to check for duplicates: %w", err)
	}

	if exists {
		return -1, api.StatusErrorf(http.StatusConflict, "This \"sites\" entry already exists")
	}

	args := make([]any, 4)

	// Populate the statement arguments.
	args[0] = object.Name
	args[1] = object.Addresses
	args[2] = object.Type
	args[3] = object.Description

	// Prepared statement to use.
	stmt, err := cluster.Stmt(tx, siteCreate)
	if err != nil {
		return -1, fmt.Errorf("Failed to get \"siteCreate\" prepared statement: %w", err)
	}

	// Execute the statement.
	result, err := stmt.Exec(args...)
	if err != nil {
		return -1, fmt.Errorf("Failed to create \"sites\" entry: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return -1, fmt.Errorf("Failed to fetch \"sites\" entry ID: %w", err)
	}

	return id, nil
}

// UpdateSite updates the Site matching the given key parameters.
// generator: Site Update
func UpdateSite(ctx context.Context, tx *sql.Tx, name string, object Site) error {
	id, err := GetSiteID(ctx, tx, name)
	if err != nil {
		return err
	}

	stmt, err := cluster.Stmt(tx, siteUpdate)
	if err != nil {
		return fmt.Errorf("Failed to get \"siteUpdate\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(object.Name, object.Addresses, object.Type, object.Description, id)
	if err != nil {
		return fmt.Errorf("Update \"sites\" entry failed: %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n != 1 {
		return fmt.Errorf("Query updated %d rows instead of 1", n)
	}

	return nil
}

// DeleteSite deletes the Site matching the given key parameters.
// generator: Site DeleteOne-by-Name
func DeleteSite(ctx context.Context, tx *sql.Tx, name string) error {
	stmt, err := cluster.Stmt(tx, siteDeleteByName)
	if err != nil {
		return fmt.Errorf("Failed to get \"siteDeleteByName\" prepared statement: %w", err)
	}

	result, err := stmt.Exec(name)
	if err != nil {
		return fmt.Errorf("Delete \"sites\": %w", err)
	}

	n, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("Fetch affected rows: %w", err)
	}

	if n == 0 {
		return api.StatusErrorf(http.StatusNotFound, "Site not found")
	} else if n > 1 {
		return fmt.Errorf("Query deleted %d Site rows instead of 1", n)
	}

	return nil
}
