name: Triaging
on:
  pull_request_target:
  issues:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read

jobs:
  label:
    if: github.event.pull_request
    permissions:
      contents: read  # for actions/labeler to determine modified files
      pull-requests: write  # for actions/labeler to add labels to PRs
    name: PR labels
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
